### PR TITLE
Add support for Expressions as conditions in CriteriaBuilder CASE expressions

### PR DESCRIPTION
**Pull request by dazey3**
for #315 

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Review by lukasj — APPROVED** [review]
looks good to me; objections from anyone?

**Comment by dazey3** [comment]
@lukasj  I was hoping that any discussions or objections would occur on the associated issue, but its been almost a year and no one has commented. So I put together this PR to push it forward a bit more. Thanks for taking a look and asking for more discussion!

**Comment by lukasj** [comment]
can you link the issue from this PR, please? (see the linked issues list in the column on right...)

**Review by beikov — APPROVED** [review]

**Comment by lukasj** [comment]
thanks @beikov , merging this...

**Pull request merged**
