### PR TITLE
#77: EntityManager(Factory) should implement AutoCloseable

### LINKED ISSUE #77: EntityManager(Factory) should implement AutoCloseable
<tt>EntityManager</tt> and <tt>EntityManagerFactory</tt> have <tt>#close()</tt> methods but do not implement <tt>AutoCloseable</tt>. Implementing <tt>AutoCloseable</tt> would allow them to be used in Java 7 try-with-resource statement.

### PR DESCRIPTION
**Pull request by lukasj**
Fixes #77

### CODE REVIEW

**Review by dmatej — APPROVED** [review]
Wow! I always wished this! :)

**Review by dmatej — APPROVED** [review]

**Review by m0mus — APPROVED** [review]
LGTM

**Review by arjantijms — APPROVED** [review]
About time :)

**Comment by tofflos** [comment]
OMG :)

**Pull request merged**
