### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by lukasj** [comment]
hmm, this change actually broke javadoc build - javadoc relied on that import; I'll fix this in upcoming PR

**Comment by pzygielo** [comment]
> hmm, this change actually broke javadoc build - javadoc relied on that import; 

I'm sorry. Now I see references in link tags indeed. But how did you check it? I called
```
mvn javadoc:javadoc
```
and it completed with success... Among many warnings I see none about unresolved references.

> I'll fix this in upcoming PR

I can use FQN in javadoc comment to fix my mistake as well.

**Comment by lukasj** [comment]
> But how did you check it?

I'm almost always running release-like build on my end - `mvn -U -C clean install -Poss-release` (pass also `-Dgpg.skip=true` to it if you don't have gpg set up)

FIx has been submitted in #251 
I'm also going to set up travis build to catch this kind of things sooner

**Comment by pzygielo** [comment]
Thank you. Please forgive the troubles.

**Comment by lukasj** [comment]
no problem.

**Pull request merged**
